# Generated by Django 5.0.4 on 2024-05-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_pwd', models.CharField(max_length=20)),
                ('emp_email', models.EmailField(max_length=20)),
                ('emp_mob', models.BigIntegerField()),
                ('emp_dept', models.CharField(max_length=8)),
                ('emp_dob', models.DateField()),
            ],
        ),
    ]
