# Generated by Django 5.0.4 on 2024-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedata',
            name='emp_img',
            field=models.ImageField(null=True, upload_to='uploadedFiles'),
        ),
    ]
