# Generated by Django 5.0.4 on 2024-05-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_employeedata_emp_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(max_length=10)),
                ('r_no', models.IntegerField()),
                ('r_dfrom', models.DateField()),
                ('r_dto', models.DateField()),
                ('r_payment', models.CharField(max_length=15)),
            ],
        ),
    ]
