# Generated by Django 5.0.4 on 2024-05-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_mob', models.BigIntegerField()),
                ('user_email', models.EmailField(max_length=20)),
                ('user_pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
