# Generated by Django 5.0.4 on 2024-05-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='r_unm',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
